// @vitest-environment jsdom
import {beforeEach,afterEach,it,expect,vi} from 'vitest';
import {OrthographicCamera} from 'three';
import * as pan from '../src/camera-pan';
const pointer=(canvas:HTMLElement,type:string,id=1,x=100,y=100)=>canvas.dispatchEvent(Object.assign(new Event(type,{bubbles:true,cancelable:true}),{pointerId:id,clientX:x,clientY:y,button:0}));
beforeEach(()=>vi.useFakeTimers());afterEach(()=>{vi.useRealTimers();vi.unstubAllGlobals();});
function setup(){const canvas=document.createElement('canvas');const move=vi.fn(),tap=vi.fn(),start=vi.fn();const controls=pan.attachCameraPan(canvas,{move,tap,start});return {canvas,move,tap,start,controls};}
it('requires a short hold then tracks every movement immediately until release',()=>{const {canvas,move,start,controls}=setup();pointer(canvas,'pointerdown');vi.advanceTimersByTime(279);expect(start).not.toHaveBeenCalled();vi.advanceTimersByTime(1);expect(start).toHaveBeenCalledOnce();pointer(canvas,'pointermove',1,120,130);pointer(canvas,'pointermove',1,125,140);expect(move.mock.calls).toEqual([[20,30],[5,10]]);pointer(canvas,'pointerup');expect(controls.active()).toBe(false);controls.dispose();});
it('preserves tap and rejects an early swipe instead of jumping after a late hold',()=>{const {canvas,move,tap,start,controls}=setup();pointer(canvas,'pointerdown');pointer(canvas,'pointerup',1,102,101);expect(tap).toHaveBeenCalledWith(102,101);pointer(canvas,'pointerdown');pointer(canvas,'pointermove',1,111,100);vi.advanceTimersByTime(500);pointer(canvas,'pointerup',1,111,100);expect(move).not.toHaveBeenCalled();expect(start).not.toHaveBeenCalled();expect(tap).toHaveBeenCalledOnce();controls.dispose();});
it.each(['pointercancel','lostpointercapture'])('cancels %s without selection or a stale drag',kind=>{const {canvas,move,tap,controls}=setup();pointer(canvas,'pointerdown');vi.advanceTimersByTime(280);pointer(canvas,kind);pointer(canvas,'pointermove',1,130,150);pointer(canvas,'pointerup');expect(move).not.toHaveBeenCalled();expect(tap).not.toHaveBeenCalled();controls.dispose();});
it('multitouch cannot turn into a one-finger drag until every pointer is released',()=>{const {canvas,move,start,controls}=setup();pointer(canvas,'pointerdown');vi.advanceTimersByTime(280);pointer(canvas,'pointerdown',2);pointer(canvas,'pointerup',2);pointer(canvas,'pointermove',1,150,150);expect(move).not.toHaveBeenCalled();pointer(canvas,'pointerup');pointer(canvas,'pointerdown');vi.advanceTimersByTime(280);pointer(canvas,'pointermove',1,140,120);expect(move).toHaveBeenCalledOnce();expect(start).toHaveBeenCalledTimes(2);controls.dispose();});
it('cancels on blur, explicit resize cancellation and disposal',()=>{const {canvas,move,tap,controls}=setup();pointer(canvas,'pointerdown');window.dispatchEvent(new Event('blur'));vi.advanceTimersByTime(300);pointer(canvas,'pointerup');expect(tap).not.toHaveBeenCalled();pointer(canvas,'pointerdown');controls.cancel();vi.advanceTimersByTime(300);pointer(canvas,'pointermove',1,140,120);expect(move).not.toHaveBeenCalled();controls.dispose();expect(vi.getTimerCount()).toBe(0);});
it('maps screen deltas onto the ground and clamps pan targets without changing zoom',()=>{const camera=new OrthographicCamera(-10,10,15,-15,.1,150);camera.position.set(15,34,43);camera.lookAt(0,.7,0);camera.updateMatrixWorld();const d=pan.groundPanDelta(camera,100,0,400,600);expect(d[0]).toBeLessThan(0);expect(d.every(Number.isFinite)).toBe(true);expect(pan.clampPan(1e6,-1e6)).toEqual([6,-18]);expect(pan.groundPanDelta(camera,100,0,0,0)).toEqual([0,0]);});
